---
- name: Download and Install Prometheus
  hosts: vm
  tasks: 
      - name: Update all packages to their latest version
        ansible.builtin.apt:
            name: "*"
            state: latest

      - name: Download the Latest Promethus (3.4.1)
        ansible.builtin.get_url:
          url: https://github.com/prometheus/prometheus/releases/download/v3.4.1/prometheus-3.4.1.linux-amd64.tar.gz   # Choose The Correct File According to the CPU Architecture. Otherwise Service won't work
          dest: /home/roshan

      - name: Extract the Content in the Same Directory and Move The Binaries to bin directory # Use Shell Module Becuase Has to done Multiple things. There is no package manager way to install this
        ansible.builtin.shell: |
            tar xzvf /home/roshan/prometheus-3.4.1.linux-amd64.tar.gz
            cd /home/roshan/prometheus-3.4.1.linux-amd64
            mkdir -p /usr/local/bin/prometheus/
            mv  prometheus prometheus.yml  /usr/local/bin/prometheus/

      
      - name: Create the Unit File 
        ansible.builtin.template:
          src: prometheus_service.j2 # Use relative path because file is in the same location
          dest: /etc/systemd/system/prometheus.service  # Service Path
          owner: root
          group: root
          mode: 0644

      - name: Start and Enable the Prometheus Service 
        ansible.builtin.service:
           name: prometheus
           state: started
           enabled : true

         



        